/** Prompt words only — not a song catalog. Random fights search Deezer with these. */
export const TITLE_SEEDS = [
  "Baby",
  "Stay",
  "Hello",
  "Love",
  "Home",
  "Sorry",
  "Ghost",
  "Crazy",
  "Drive",
  "Fire",
  "Dreams",
  "Angel",
  "Heaven",
  "Hero",
  "Trouble",
  "Miracle",
  "Poison",
  "Runaway",
  "Midnight",
  "Alone",
  "Smile",
  "Perfect",
  "Forever",
  "Falling",
  "Happy",
  "Hurt",
  "Lights",
  "Lost",
  "Magic",
  "Memories",
  "Monster",
  "Numb",
  "Paradise",
  "River",
  "Stars",
  "Sunflower",
  "Thunder",
  "Waves",
  "Yesterday",
  "Closer",
  "Halo",
  "Lonely",
  "Mercy",
  "Money",
  "Ocean",
  "Roses",
  "Sugar",
  "Toxic",
  "Unholy",
  "Wild",
];

export function randomSeed(exclude: string[] = []): string {
  const blocked = new Set(exclude.map((item) => item.toLowerCase()));
  const pool = TITLE_SEEDS.filter((seed) => !blocked.has(seed.toLowerCase()));
  const source = pool.length > 0 ? pool : TITLE_SEEDS;
  return source[Math.floor(Math.random() * source.length)];
}
